
DROP TABLE Utilisateur CASCADE;
DROP TABLE OffreRectrument CASCADE;
DROP TABLE Rang CASCADE;
DROP TABLE Message CASCADE;
DROP TABLE Sujet CASCADE;
DROP TABLE Categorie CASCADE;
DROP TABLE Support CASCADE;
DROP TABLE Statistiques CASCADE;
DROP TABLE MsgPrive CASCADE;
DROP TABLE Programmation CASCADE;
DROP TABLE UtilisateurProgrammation CASCADE;
DROP TABLE OffreRecrutementProgrammation CASCADE;

DROP DOMAIN Status CASCADE;
DROP DOMAIN DomRang CASCADE;
DROP DOMAIN OS CASCADE;
DROP DOMAIN WebBrowser CASCADE;
DROP DOMAIN Heures CASCADE;
DROP DOMAIN Annonce CASCADE;
DROP DOMAIN Contrat CASCADE;
DROP DOMAIN Langage CASCADE;
DROP DOMAIN Niveau CASCADE;



DROP SCHEMA Eforum CASCADE;
